<?php

namespace Container3tJkPts;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EVvsBjdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EVvsBjd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EVvsBjd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ProductApiController::create' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProductApiController::delete' => ['privates', '.service_locator.OE1bLno', 'get_ServiceLocator_OE1bLnoService', true],
            'App\\Controller\\ProductApiController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProductApiController::show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\ProductApiController::update' => ['privates', '.service_locator.OE1bLno', 'get_ServiceLocator_OE1bLnoService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ProductApiController:create' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProductApiController:delete' => ['privates', '.service_locator.OE1bLno', 'get_ServiceLocator_OE1bLnoService', true],
            'App\\Controller\\ProductApiController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProductApiController:show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\ProductApiController:update' => ['privates', '.service_locator.OE1bLno', 'get_ServiceLocator_OE1bLnoService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ProductApiController::create' => '?',
            'App\\Controller\\ProductApiController::delete' => '?',
            'App\\Controller\\ProductApiController::index' => '?',
            'App\\Controller\\ProductApiController::show' => '?',
            'App\\Controller\\ProductApiController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProductApiController:create' => '?',
            'App\\Controller\\ProductApiController:delete' => '?',
            'App\\Controller\\ProductApiController:index' => '?',
            'App\\Controller\\ProductApiController:show' => '?',
            'App\\Controller\\ProductApiController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
