<?php

namespace ContainerBipYgvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RNb2kNYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RNb2kNY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RNb2kNY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CategoryApiController::create' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CategoryApiController::delete' => ['privates', '.service_locator.gKPBAx1', 'get_ServiceLocator_GKPBAx1Service', true],
            'App\\Controller\\CategoryApiController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CategoryApiController::show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\CategoryApiController::update' => ['privates', '.service_locator.gKPBAx1', 'get_ServiceLocator_GKPBAx1Service', true],
            'App\\Controller\\ProductApiController::create' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProductApiController::delete' => ['privates', '.service_locator.OE1bLno', 'get_ServiceLocator_OE1bLnoService', true],
            'App\\Controller\\ProductApiController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProductApiController::show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\ProductApiController::update' => ['privates', '.service_locator.OE1bLno', 'get_ServiceLocator_OE1bLnoService', true],
            'App\\Controller\\UserApiController::create' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserApiController::delete' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserApiController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserApiController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserApiController::update' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategoryApiController:create' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CategoryApiController:delete' => ['privates', '.service_locator.gKPBAx1', 'get_ServiceLocator_GKPBAx1Service', true],
            'App\\Controller\\CategoryApiController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CategoryApiController:show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\CategoryApiController:update' => ['privates', '.service_locator.gKPBAx1', 'get_ServiceLocator_GKPBAx1Service', true],
            'App\\Controller\\ProductApiController:create' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProductApiController:delete' => ['privates', '.service_locator.OE1bLno', 'get_ServiceLocator_OE1bLnoService', true],
            'App\\Controller\\ProductApiController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProductApiController:show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\ProductApiController:update' => ['privates', '.service_locator.OE1bLno', 'get_ServiceLocator_OE1bLnoService', true],
            'App\\Controller\\UserApiController:create' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserApiController:delete' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserApiController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserApiController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserApiController:update' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategoryApiController::create' => '?',
            'App\\Controller\\CategoryApiController::delete' => '?',
            'App\\Controller\\CategoryApiController::index' => '?',
            'App\\Controller\\CategoryApiController::show' => '?',
            'App\\Controller\\CategoryApiController::update' => '?',
            'App\\Controller\\ProductApiController::create' => '?',
            'App\\Controller\\ProductApiController::delete' => '?',
            'App\\Controller\\ProductApiController::index' => '?',
            'App\\Controller\\ProductApiController::show' => '?',
            'App\\Controller\\ProductApiController::update' => '?',
            'App\\Controller\\UserApiController::create' => '?',
            'App\\Controller\\UserApiController::delete' => '?',
            'App\\Controller\\UserApiController::index' => '?',
            'App\\Controller\\UserApiController::show' => '?',
            'App\\Controller\\UserApiController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoryApiController:create' => '?',
            'App\\Controller\\CategoryApiController:delete' => '?',
            'App\\Controller\\CategoryApiController:index' => '?',
            'App\\Controller\\CategoryApiController:show' => '?',
            'App\\Controller\\CategoryApiController:update' => '?',
            'App\\Controller\\ProductApiController:create' => '?',
            'App\\Controller\\ProductApiController:delete' => '?',
            'App\\Controller\\ProductApiController:index' => '?',
            'App\\Controller\\ProductApiController:show' => '?',
            'App\\Controller\\ProductApiController:update' => '?',
            'App\\Controller\\UserApiController:create' => '?',
            'App\\Controller\\UserApiController:delete' => '?',
            'App\\Controller\\UserApiController:index' => '?',
            'App\\Controller\\UserApiController:show' => '?',
            'App\\Controller\\UserApiController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
