<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOM7blsA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOM7blsA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOM7blsA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOM7blsA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOM7blsA\App_KernelDevDebugContainer([
    'container.build_hash' => 'OM7blsA',
    'container.build_id' => '174bcf27',
    'container.build_time' => 1774274143,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOM7blsA');
